# Default values for smk-namespace-init.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

# Default values for helm-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

env: dev
app_name: smk_init

github_actions_sa:
  name: gha-sa
  role_name: gha-sa-role
  role_binding_name: gha-sa-rolebinding

app_image_pull_secret_params:
  name: image-pull-secrets
  email: guy.lafleur@montreal.canadians.ca
  username: guyLafleur
  password: b05t0NSuuuuuxx999342
  registry: docker.pkg.github.com/bcgov/smk-fc-fap/smk-fc-fap
  imagetag: latest

kong_config:
  secrets_name: kong-secrets
  secret_key_name: kong-config
  gwa_client_id: name-of-kong-config-service-account
  gwa_namespace: the-gwa-namespace
  apikey: api-key-that-goes-with-the-service-account
  aps_nsp_name: aps-gateway-to-your-upstream-api
  gwa_env: test
  kong_test_project_name: 264e6f-test
  kong_prod_project_name: 264e6f-prod

# Used to ensure the correct namespace has been set by gha
namespaces_configmap:
  name: namespaces-cm
  dev: name_of_dev_namespace
  test: name_of_test_namespace
  prod: name_of_prod_namespace

